### ISSUE TITLE
Broken in IE11 when built with Webpack

### ISSUE THREAD

**Issue by ben-x9** [gcanti/monocle-ts#103]
The package.json file includes `main` and `module` fields but is missing a `browser` field.

The result is that when building with `target` set to `web` the import resolves to `module` which points to `es6/index.js` which includes arrow functions that break in IE11.

To fix this add a `browser` field to package.json that points to `lib/index.js`:

```
"main": "lib/index.js",
"module": "es6/index.js",
"browser:" "lib/index.js",
```

see: https://webpack.js.org/configuration/resolve/#resolvemainfields

**Comment by ben-x9** [comment]
Same issue as https://github.com/gcanti/fp-ts/issues/1110

**Comment by gcanti** [comment]
@ben-x9 `monocle-ts` [looks ok](https://github.com/gcanti/monocle-ts/blob/8df85f02db6012ae10f0ab8d018f1d14b1307654/tsconfig.es6.json), the culprit should be `fp-ts`

**Comment by gcanti** [comment]
`fp-ts@2.4.3` released, could you please try it out?

**Comment by ben-x9** [comment]
Yes you're right. Tested with fp-ts@2.4.3 and it works.

My teammate also changed imports from monocle-ts to monocle-ts/lib so I assumed it was both, my bad!
