### ISSUE TITLE
Using `set` of `composeOptional` broke by latest update.

### ISSUE THREAD

**Issue by pmartin-cogility** [gcanti/monocle-ts#108]
## 🐛 Bug report

The added `null` check here https://github.com/gcanti/monocle-ts/blob/master/src/index.ts#L824
appears to have caused `set` of `composeOptional` to not set the given value.

### Your environment
React application

Which versions of monocle-ts are affected by this issue? Did this work in previous versions of monocle-ts?
Affected in v2.1.0
Works in v2.0.1

| Software   | Version(s) |
| ---------- | ---------- |
| monocle-ts |    2.1.0        |
| fp-ts      |       2.4.3     |
| TypeScript |     3.6.4       |

**Comment by gcanti** [comment]
Looks like the intended bug fix (reference https://github.com/gcanti/monocle-ts/issues/106)

Optional laws:

1. getOption(s).fold(() => s, a => set(a)(s)) = s
2. **getOption(set(a)(s)) = getOption(s).map(_ => a)**
3. set(a)(set(a)(s)) = set(a)(s)

If `getOption(s)` returns `none` then `set` shouldn't set the given value

**Comment by pmartin-cogility** [comment]
Your right. Thanks for the clarification.

**Comment by jleider** [comment]
I am running into this same issue with the update to 2.1.0. If an optional lens can not be used to set a potentially nullable value, is there another mechanism for setting values where the key could possibly be undefined?

```typescript
import { Optional } from "monocle-ts";

interface Foo {
  bar: string
}

const f: Partial<Foo> = {};

const l = Optional.fromPath<Partial<Foo>>()(["bar"]);

console.log(l.getOption(f)); // returns None
console.log(l.set("barString")(f)); // returns {}
console.log(l.getOption(f)); // returns None
```

**Comment by gcanti** [comment]
@jleider with a `Lens`

```ts
const lens = Lens.fromProp<Partial<Foo>>()('bar')
const f2 = lens.set('barString')(f)
```
