### ISSUE TITLE
Improve Lens reusability

### ISSUE THREAD

**Issue by patroza** [gcanti/monocle-ts#111]
### Current Behavior

Currently the return type of a modification when using a Lens, is the same return type as the type that the Lens was configured for.

### Desired Behavior

The return type of a modification should be the same type as the Input Value instead.

### Suggested Solution

Adjust the interfaces so that we infer the input value type, make sure that it extends the type of the Lens, and then return the same type as the input value.

Sample adapter I'm using for the `modify` function atm:
```typescript
interface CoolLens<TRequired, TValue> extends Lens<TRequired, TValue> {
  modify(f: (a: TValue) => TValue): <TGiven extends TRequired>(s: TGiven) => TGiven
}

export const convertCoolLens = <TRequired, TValue>(l: Lens<TRequired, TValue>) =>
  l as CoolLens<TRequired, TValue>
```

`const startDateL = convertCoolLens(Lens.fromPath<Pick<TrainTrip, "startDate">>()(["startDate"]))`

If I put a TrainTrip in, I get a TrainTrip out. If I get something that looks like an object with `startDate` with the right type, I get that type out too.

### Who does this impact? Who is this for?

Myself, and anyone else who wants to re-use Lenses based on (partial) interfaces.

### Describe alternatives you've considered

Using custom adapter from my side, but it gets tedious.

**Comment by gcanti** [comment]
@patroza that operation is not legit. Counterexample:

```ts
import { Lens } from 'monocle-ts'

const lens: Lens<{ a: string; b: number }, number> = new Lens(
  (s) => s.b,
  (b) => (s) => ({ a: s.a, b })
)

interface CoolLens<S, A> extends Lens<S, A> {
  modify(f: (a: A) => A): <R extends S>(r: R) => R
}

export const convertCoolLens = <S, A>(l: Lens<S, A>) => l as CoolLens<S, A>

const coolLens = convertCoolLens(lens)

const x = coolLens.modify((n) => n * 2)({ a: 'a', b: 2, c: true })
console.log(x.c) // => undefined
```

`x` has type

```ts
const x: {
    a: string;
    b: number;
    c: boolean;
}
```

but is not true

**Comment by patroza** [comment]
@gcanti fair enough. There would be more plumbing necessary indeed, and the second argument to the Lens would need to restore original, and only adjust the field in question.
`(b) => (s) => ({ ...s, b })`, it's what I understand the built-ins to do, but as long as you could create a Lens where you are destructive, it would indeed be a lie.
