### ISSUE TITLE
How to get property name used in Lens.fromProp

### ISSUE THREAD

**Issue by waynevanson** [gcanti/monocle-ts#112]
### Current Behavior

There is no way to get the prop used from `Lens.fromProp` to my knowledge.

Currently we can only get the value and set the value.

### Desired Behavior

Read the prop name from the lens as a property of the lens.

```ts
const lens = Lens.fromProp()('age')

assert(lens.prop).toBe('age')
```

### Suggested Solution

Add the prop as a variable within prop.

### Who does this impact? Who is this for?

All users. Not a breaking change ~~in any way.~~

Since we're adding a generic, users who use these generics to construct types may find their code not working.

Generics would be added for `Lens` and any other type that composes with Lens.

### Describe alternatives you've considered

I was looking for a function that might retrieve this. The prop in the src code reveals that it's not saved as a property anywhere. Instead, it is kept in scope via closures.

### Additional context

This reveals that this request it out of scope from what Lens libraries usually provide.
https://stackoverflow.com/questions/44454873/how-to-print-a-monocle-lens-as-a-property-accessor-style-string

Thank you for all your libraries! I love FP now <3 Is there a place for donations?

**Comment by kylegoetz** [comment]
What should `lens.prop` be if lens is the composition of two other lenses? Let's say it would be `${lens1.prop}.${lens2.prop}`. But then we have a problem if we have a record like this:

```
interface State {
  foo: {
    bar: number
  }
  'foo.bar': boolean
}

// _foo.compose(_bar).prop := 'foo.bar'
```

But that would be the name of Lens.fromProp()('foo.bar')

This would hold true for any possible string concatenation we could envision.

**Comment by waynevanson** [comment]
I think we discussed this in another issue as well.  It's shouldn't be a lens,  but could be something else.
