### ISSUE TITLE
Traversal + fp-ts array are not compatible

### ISSUE THREAD

**Issue by kylegoetz** [gcanti/monocle-ts#121]
## 🐛 Bug report

I can't seem to get `fromTraversable(array)` to not produce an error.

### Current Behavior

```
import { Lens, fromTraversable, Prism } from "monocle-ts";
import { array } from "fp-ts/lib/Array";

const contactTraversal = fromTraversable(array)<Contact.Domain>() // Argument of type Monad1<"Array"> ... is not assignable to parameter of type Traversable<Domain>. The types returned by traverse(...) are incompatible between those types
```

### Expected behavior

That, like in the examples provided in the API docs + examples in the issue tracker here, I do not get a type error.

### Your environment

* `"monocle-ts": "^2.1.0"`
* `"fp-ts": "^2.5.3"`
* `"typescript": "^3.9.2"`

**Comment by gcanti** [comment]
@kylegoetz I can't repro, this is working fine in my setup

```ts
import { array } from 'fp-ts/lib/Array'
import { fromTraversable } from 'monocle-ts'

// const x: Traversal<string[], string>
const x = fromTraversable(array)<string>() // ok
```

**Comment by kylegoetz** [comment]
Ok I'll try to do as minimal setup. Looks like some reason URIS doesn't include array or my linter doesn't think so, which affects what belongs to the traversable1 type (not array). Will comment here if I am able to reproduce with minimal setup.
