### ISSUE TITLE
Drop class encoding

### ISSUE THREAD

**Issue by gcanti** [gcanti/monocle-ts#129]
## 🚀 Feature request

RE: https://github.com/gcanti/monocle-ts/pull/126

### Desired Behavior

```ts
import { array } from 'fp-ts/lib/Array'
import { pipe } from 'fp-ts/lib/function'
import { Option } from 'fp-ts/lib/Option'
import { record } from 'fp-ts/lib/Record'
import * as L from '../src/Lens'
import * as T from '../src/Traversal'

interface NestedValue {
  baz: string
}

interface Value {
  nested: Option<Array<NestedValue>>
}

interface Item {
  readonly foo: Record<string, Value>
}

interface Data {
  readonly items: Array<Item>
}

export const x: T.Traversal<Data, string> = pipe(
  L.id<Data>(),
  L.prop('items'),
  L.traverse(array),
  T.prop('foo'),
  T.traverse(record),
  T.prop('nested'),
  T.some,
  T.index(2),
  T.prop('baz')
)
```

**Comment by chrisber** [comment]
I think this is truly amazing, thanks for putting all the effort in.

By the way, have you joined the `GitHub Sponsors` waiting list? I would like to contribute, it will not be much, but at least I can my appreciation.

**Comment by gcanti** [comment]
> By the way, have you joined the GitHub Sponsors waiting list?

@chrisber no, but thanks, I appreciate the thought

@raveclassic other than `prop`, `props`, `traverse` and `index` I added

- `component` (similar to `prop` but for tuples)
- `key` (similar to `index` but for records)

**Comment by gcanti** [comment]
Closed by https://github.com/gcanti/monocle-ts/pull/130
