### ISSUE TITLE
findFirst combinator

### ISSUE THREAD

**Issue by VincentQuillien** [gcanti/monocle-ts#131]
## 🚀 Feature request

It would be practical to have a findFirst combinator taking a predicate and a Lens focused on an Array. It would return an Optional focused on the first element that satisfies the predicate.

### Desired Behavior
```ts
declare function findFirst: <A>(f: (a: A) => boolean) => <S>(l: Lens<S, A[]>) => Optional<S, A>;

import * as L from 'monocle/lib/Lens';

interface Test {
  a: number[];
}

pipe(L.id<Test>(), L.prop('a'), L.findFirst(x => x === 42)) // --> Optional<Test, number>

```

**Comment by gcanti** [comment]
@VincentQuillien looks good to me, `findFirst` should work with `ReadonlyArray`s though

```ts
declare const findFirst: <A>(predicate: Predicate<A>) => <S>(sa: L.Lens<S, ReadonlyArray<A>>) => Optional<S, A>

interface Test {
  readonly a: ReadonlyArray<number>
}
```
