### ISSUE TITLE
Unable to set a new value to a Prism

### ISSUE THREAD

**Issue by skysantalucial** [gcanti/monocle-ts#144]
## 🐛 Bug report
Hello! I stumbled on a problem while experimenting with the examples. Seems like setting a new value to a Prism is no more possible

### Current Behavior

```ts
interface Person {
  name: string
  surname: Option<string>
}

const surname = Lens.fromProp<Person>()('surname').composePrism(Prism.some<string>())

const p: Person = { name: 'Giulio', surname: none }

console.log(surname.getOption(p)) // => None
console.log(surname.set('Canti')(p)) // => { name: 'Giulio', surname: None }
```

### Expected behavior

```ts
interface Person {
  name: string
  surname: Option<string>
}

const surname = Lens.fromProp<Person>()('surname').composePrism(Prism.some<string>())

const p: Person = { name: 'Giulio', surname: none }

console.log(surname.getOption(p)) // => None
console.log(surname.set('Canti')(p)) // => { name: 'Giulio', surname: Some("Canti") }
```

### Your environment

According to my tests this behavior appeared from version 2.0.1

| Software   | Version(s) |
| ---------- | ---------- |
| monocle-ts | 2.3.3 |
| fp-ts      | 2.8.4 |
| TypeScript | 4.1.2 |

**Comment by gcanti** [comment]
@skysantalucial the current behavior is correct according to the `Optional` laws

1. pipe(getOption(s), fold(() => s, a => set(a)(s))) = s
2. **getOption(set(a)(s)) = pipe(getOption(s), map(_ => a))**
3. set(a)(set(a)(s)) = set(a)(s)

**Comment by skysantalucial** [comment]
Ok, so it's just a matter of updating the [examples](https://github.com/gcanti/monocle-ts/blob/master/examples/Optional.ts)

In this case how can i go from this `{ name: 'Laura', surname: none }` to this `{ name: 'Laura', surname: Some("Santalucia") }` using an `Optional`? Is it possibile?

**Comment by gcanti** [comment]
> Ok, so it's just a matter of updating the examples

Yup, thanks for pointing out.

> using an Optional? Is it possibile?

No it isn't, you need a `Lens`

```ts
const surname = Lens.fromProp<Person>()('surname')

const p: Person = { name: 'Giulio', surname: none }

console.log(surname.set(some('Canti'))(p)) // => { name: 'Giulio', surname: Some("Canti") }
```

**Comment by skysantalucial** [comment]
understood 👍 thanks for the help
