### ISSUE TITLE
Import without `/lib` or `/es6` paths like fp-ts now does

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/monocle-ts#147]
Same as https://github.com/gcanti/io-ts/issues/506 but as it applies to monocle-ts.

**Comment by gcanti** [comment]
@OliverJAsh just released v2.3.6 in the next channel (`npm i monocle-ts@next`), could you please try it out?

**Comment by OliverJAsh** [comment]
Yup it works!

**Comment by gcanti** [comment]
Awesome, thank you (released as `latest`).
