### ISSUE TITLE
more prisms out of the box

### ISSUE THREAD

**Issue by leemhenson** [gcanti/monocle-ts#15]
Would you be interested in having a few more prisms besides `Prism.some` defined in this package? So far I've found these two useful also:

```typescript
import { head } from "fp-ts/lib/Array";
import { fromNullable } from "fp-ts/lib/Option";

function headPrism<A>() {
  return new Prism<A[], A>(
    head,
    a => [a],
  );
}

function fromNullablePrism<A>() {
  return new Prism<Option<A>, A>(
    s => s,
    a => fromNullable(a));
}
```

**Comment by gcanti** [comment]
Sure. Not sure those are actually prisms though:

`headPrism` should be an `Optional` based on the main example here http://julien-truffaut.github.io/Monocle/optics/optional.html

`fromNullablePrism` is equivalent to `some` since `a: A` can't be nully

**Comment by leemhenson** [comment]
> headPrism should be an Optional based on the main example here http://julien-truffaut.github.io/Monocle/optics/optional.html

Haha. I think I got that because I read _some guy_'s blog (https://medium.com/@gcanti/introduction-to-optics-lenses-and-prisms-3230e73bfcfe) where it said:

> Prism is for working with sum types (e.g. maybe types, union types) and _arrays_.

When you say:

> fromNullablePrism is equivalent to some since a: A can't be nully

So this is going back to what I originally wrote in #7. I'm trying to update a deeply nested `Option<A>` field so it becomes `null`. `Prism.some` will set it to `some(null)` which I don't want. `fromNullablePrism` works for me, but am I now violating some law that will come back to bite me if I compose this with something else?

**Comment by gcanti** [comment]
> I think I got that because I read some guy's blog 

The `Prism` shown there is more a `Optional` in the monocle parlance. However re-reading the post it seems to suffer from the same mistake I made with `Optional.fromProp`, namely in this example

```ts
const first: Prism<string, string> = {
  get: s => s ? s.substring(0, 1) : null,
  set: (a, s) => a + s.substring(1)
}
```

I guess should be 

```ts
const first: Prism<string, string> = {
  get: s => s ? s.substring(0, 1) : null,
  set: (a, s) => s.length ? a + s.substring(1) : ''
}
```

I think it's better to amend or remove that post, I apologize for the confusion.

> I'm trying to update a deeply nested `Option<A>` field so it becomes `null`

Mhhh then I'm not sure I'm following, are you trying to handle `A | null` or `Option<A>`?

**Comment by gcanti** [comment]
Maybe this?

```ts
import { Lens, Optional, Prism } from '../src'
import { Option, some, none, fromNullable } from 'fp-ts/lib/Option'

interface Bar {
  s: Option<string>
}

interface Foo {
  bar: Option<Bar>
}

const foo: Foo = {
  bar: some({
    s: some('blah')
  })
}

const barLens = Lens.fromProp<Foo, 'bar'>('bar')
const sLens = Lens.fromProp<Bar, 's'>('s')

const sOptional = barLens
  .composePrism(Prism.some<Bar>())
  .composeLens(sLens)
  .composePrism(Prism.some<string>())

console.log(sOptional.set('WHOP', foo)) // { bar: Some({"s":{"value":"WHOP","_tag":"Some"}}) }

// allows for setting none
const optionsOptional = barLens
  .composePrism(Prism.some<Bar>())
  .composeLens(sLens) // <= note the missing .composePrism(Prism.some<string>()) here

console.log(optionsOptional.set(none, foo)) // { bar: Some({"s":{"_tag":"None"}}) }
```

**Comment by gcanti** [comment]
@leemhenson any progress?

**Comment by leemhenson** [comment]
Hey, sorry I should have closed this issue. Yep, those latest set of changes has helped and now I don't really need anything more than the `some` and `predicate` prisms already provided.
