### ISSUE TITLE
Release 2.3.8 seems to be broken

### ISSUE THREAD

**Issue by pburgmer** [gcanti/monocle-ts#159]
By reinstalling my node modules I got the latest version of monocle-ts: 2.3.8. When I try to compile my application, I get the following error:

Error: node_modules/monocle-ts/lib/Traversal.d.ts:217:41 - error TS2339: Property 'traversalTraverse' does not exist on type 'typeof import("C:/Users/burgmer.PD/PDTec/Projekte/tetra-get-started/client/node_modules/monocle-ts/lib/internal")'.

217 export declare const traverse: typeof _.traversalTraverse

**Comment by pburgmer** [comment]
Manual downgrade to 2.3.7 fixes the problem.

**Comment by gcanti** [comment]
@pburgmer thanks for the bug report, I just released a patch (v2.3.9), could you please try it out?

**Comment by pburgmer** [comment]
Works! Thanks a lot for your quick reaction.
