### ISSUE TITLE
Add Setter?

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [gcanti/monocle-ts#18]

**Comment by gcanti** [comment]
@liam-goodacre-hpe based on https://github.com/julien-truffaut/Monocle/blob/master/core/shared/src/main/scala/monocle/Setter.scala `Setter` could be defined as

```ts
export class Setter<S, A> {
  constructor(public readonly modify: (f: (a: A) => A) => (s: S) => S) {}
}
```

right?

**Comment by liam-goodacre-hpe** [comment]
Yeah that will work, although the other constructor fields aren't curried: `(f: (a: A) => A, s: S) => S` :)

**Comment by gcanti** [comment]
> although the other constructor fields aren't curried

Right. Would you like to send a PR?

**Comment by liam-goodacre-hpe** [comment]
Yes, I'll get this done later tonight.  There are other features I'd like - shall I include them in the PR and we can discuss them there?

**Comment by LiamGoodacre** [comment]
Oops, been using the wrong account :smile:
