### ISSUE TITLE
Add aliases to ISO

### ISSUE THREAD

**Issue by gcanti** [gcanti/monocle-ts#24]
get / reverseGet -> wrap / unwrap
get / reverseGet -> to / from

**Comment by justinwoo** [comment]
my only complaint about to/from is that they get me mixed up with to/from for datatype generics

**Comment by gcanti** [comment]
Maybe I could add several aliases, so you can use the suitable ones for your use case

- orginal (monocle): get / reverseGet
- newtype: wrap / unwrap
- unit of measures: to / from
