### ISSUE TITLE
Prism#asOptional produces unlawful instances?

### ISSUE THREAD

**Issue by gcanti** [gcanti/monocle-ts#29]
@LiamGoodacre I think that the current implementation of `Prism#asOptional` returns unlawful `Optionals`. 

I added this test https://github.com/gcanti/monocle-ts/blob/f4ce27d0799941d4491b1b243ca694605769cd2d/test/Prism.ts#L25

AFAIK it should fail and `optional.set(2)(none)` should return `none` otherwise the second law is violated

Optional Laws:

1. `getOption(s).fold(() => s, a => set(a)(s)) = s`
2. `getOption(set(a)(s)) = getOption(s).map(_ => a)`
3. `set(a)(set(a)(s)) = set(a)(s)`

The culprit seems the implementation of `asOptional` https://github.com/gcanti/monocle-ts/blob/f4ce27d0799941d4491b1b243ca694605769cd2d/src/index.ts#L313

I think that should be

```diff
asOptional(): Optional<S, A> {
-  return new Optional(this.getOption, a => s => this.reverseGet(a))
+  return new Optional(this.getOption, a => s => this.set(a))
}
```

`asTraversal` could suffer of the same issue since the implementation uses `reverseGet`, not sure though.

What do you think?

**Comment by LiamGoodacre** [comment]
@gcanti: Yes, what you've said is correct.  (Apologies for the delayed response).

**Comment by gcanti** [comment]
@LiamGoodacre np and thanks for the help ;)
