### ISSUE TITLE
reverse operator for Iso

### ISSUE THREAD

**Issue by sledorze** [gcanti/monocle-ts#36]
Not sure if its the best name for it.

**Comment by gcanti** [comment]
this `reverse`? https://github.com/julien-truffaut/Monocle/blob/d3a1243f58c7ee933871557e4487e4bbafa56b89/core/shared/src/main/scala/monocle/Iso.scala#L53

**Comment by sledorze** [comment]
@gcanti Yes basically but just asking for reverse on `Iso` not `PIso`
(awesome type param names btw)
