### ISSUE TITLE
Traversal over an array

### ISSUE THREAD

**Issue by rvanheest** [gcanti/monocle-ts#38]
Hi, I know Monocle from the Scala world, so I was really glad to see a port for it in TypeScript. I'm intending to use Monocle-TS inside the reducers that are required by Redux, which will hopefully make my life much easier while 'mutating' immutable objects.

I came across a use case that I could not figure out how to set up using Monocle-TS, that I was able to solve with Monocle-Scala. I was wondering if this use case is not yet implemented in this library, or if I'm overlooking something.

Given below (in Scala) are `Tweet` and `TweetsViewModel` definitions, as well as the lenses/traverals for modifying the text of a `Tweet`. I can go from `TweetsViewModel` to `List[Tweet]` using a lens, compose this with a `Traversal` over this `List[Tweet]` and finally compose this with a lens that goes from `Tweet` to `text: String`. Then, given an instance of `TweetsViewModel` I can reverse each text using a simple `modify`.

```scala
import monocle.{Lens, Traversal}
import scalaz.std.list._

case class Tweet(text: String)
case class TweetsViewModel(tweets: List[Tweet] = List.empty)

val tweetsLens = Lens[TweetsViewModel, List[Tweet]](_.tweets)(tweets => _.copy(tweets = tweets))
val tweetTraversal = Traversal.fromTraverse[List, Tweet]
val textLens = Lens[Tweet, String](_.text)(text => _.copy(text = text))

val composedLens = tweetsLens.composeTraversal(tweetTraversal).composeLens(textLens)

val tweet1 = Tweet("hello world")
val tweet2 = Tweet("foobar")
val model = TweetsViewModel(List(tweet1, tweet2))

val newModel = composedLens.modify(_.reverse)(model)
```

In Monocle-TS I can't figure out how to construct this `Traversal.fromTraverse[List, Tweet]`. I surely can do this by breaking up the composition into two parts and doing the Traversal myself as shown below, but that is not really as elegant as I was able to do it above. Shouldn't I be able to do a similar thing? Or am I overlooking something?

```typescript
interface Tweet {
    text: string
}

interface TweetViewModel {
    tweets: Tweet[]
}

const tweetsLens = Lens.fromProp<TweetViewModel, 'tweets'>('tweets')
const tweetTextLens = Lens.fromProp<Tweet, 'text'>('text')

const reverseLens = tweetsLens.modify(tweets =>
                         tweets.map(tweet =>
                             tweetTextLens.modify(text => text.split("").reverse().join(""))(tweet)
                         )
                     )

const tweet1: Tweet = { text: "hello world" }
const tweet2: Tweet = { text: "foobar" }
const model: TweetsViewModel = { tweets: [tweet1, tweet2] }

const newModel = reverseLens(model)
```

**Comment by gcanti** [comment]
@rvanheest you can use `fromTraversable` (which is the equivalent of `Traversal.fromTraverse`)

```ts
import { Lens, fromTraversable } from 'monocle-ts'
import { array } from 'fp-ts/lib/Array'

interface Tweet {
  text: string
}

interface TweetViewModel {
  tweets: Tweet[]
}

const tweetsLens = Lens.fromProp<TweetViewModel, 'tweets'>('tweets')
const tweetTextLens = Lens.fromProp<Tweet, 'text'>('text')
const tweetTraversal = fromTraversable(array)<Tweet>()
const composedTraversal = tweetsLens.composeTraversal(tweetTraversal).composeLens(tweetTextLens)

const tweet1: Tweet = { text: 'hello world' }
const tweet2: Tweet = { text: 'foobar' }
const model: TweetViewModel = { tweets: [tweet1, tweet2] }

const newModel = composedTraversal.modify(text =>
  text
    .split('')
    .reverse()
    .join('')
)(model)
```

**Comment by rvanheest** [comment]
Awesome! Thanks for the quick response. Would be great if you could add an example of this to your documentation.

**Comment by gcanti** [comment]
Good idea, may I use your example?

**Comment by rvanheest** [comment]
Of course!
