### ISSUE TITLE
Performance issues with Props.fromPath

### ISSUE THREAD

**Issue by rvanheest** [gcanti/monocle-ts#39]
Are you aware of any performance issues with `Lens.fromPath` and Webstorm? While trying out this library I ran into huge lag spikes when using this function. Other functions, like `Lens.fromProp` all work fine, but as soon as I type `Lens.fromPath()` (note: even before I have started typing an actual path), Webstorm becomes very slow (almost freezes) and every key stroke takes like 10 seconds to render.

I think this is TypeScript's type checker that has problems with this function, given it's rather complex type. Have you experienced this behavior as well (or can you replicate this) and/or do you know of any solutions for this issue?

**Comment by gcanti** [comment]
Sorry, I'm not a Webstorm user (VS Code)

**Comment by rvanheest** [comment]
Fine! I'll avoid using this function for now and use 'manual composition' until I find a solution.

**Comment by gcanti** [comment]
If I understand correctly [this](https://www.jetbrains.com/help/webstorm/typescript.html) says that you must configure Webstorm in order to use the official TypeScript Language Service

**Comment by rvanheest** [comment]
I know. Already did that. I was just experimenting with it and found that turning some of these options on/off increases/decreases the time Webstorm freezes when using `Lens.fromPath` in a file. However, the freezing time is still in the order of seconds at best, so that does not solve it!
