### ISSUE TITLE
PrismFromRegex ?

### ISSUE THREAD

**Issue by sledorze** [gcanti/monocle-ts#42]
Does a `PrismFromRegex` could be part of this library or is this library considered `core` and it should be put somewhere else?

**Comment by gcanti** [comment]
@sledorze looks covered by `fromPredicate`

```ts
Prism.fromPredicate(s => myregexp.test(s))
```

**Comment by sledorze** [comment]
Yes it could be a one liner derived from frompredicate.
I understand that the lib should be kept minimal
