### ISSUE TITLE
Best Practice creating a Lens for StrMap

### ISSUE THREAD

**Issue by mlegenhausen** [gcanti/monocle-ts#43]
I would like to know what is the best practice to get and set single elements in a `StrMap`. My naive idea would be to create `Optional` like so

```ts
const strmapLens = (k: string) => new Optional<any, any>(
  (s) => lookup(id, s),
  (s) => (a) => insert(id, a, s)
);
```

Is this the way to go or is there something that is already build in `ts-monocle`?

**Comment by gcanti** [comment]
Looks like you are looking for either [At](https://github.com/julien-truffaut/Monocle/blob/882cec9d531d9c959b5fe7be819c64cf6b7ffead/core/shared/src/main/scala/monocle/function/At.scala) or [Index](https://github.com/julien-truffaut/Monocle/blob/882cec9d531d9c959b5fe7be819c64cf6b7ffead/core/shared/src/main/scala/monocle/function/Index.scala) which are not implemented in `monocle-ts`

A possible implementation of `Index`

```ts
import { index, updateAt } from 'fp-ts/lib/Array'
import { StrMap, lookup, insert } from 'fp-ts/lib/StrMap'

class Index<S, I, A> {
  constructor(readonly ix: (i: I) => Optional<S, A>) {}
}

const listIndex = <A = never>(): Index<Array<A>, number, A> =>
  new Index(i => new Optional(s => index(i, s), a => s => updateAt(i, a, s).getOrElse(s)))

const strmapIndex = <A = never>(): Index<StrMap<A>, string, A> =>
  new Index(i => new Optional(s => lookup(i, s), a => s => lookup(i, s).fold(s, () => insert(i, a, s))))
```

Note that `StrMap.insert` always adds the value, while (if I'm not wrong) an `Optional` should behave like this

```ts
console.log(
  strmapIndex<number>()
    .ix('a')
    .set(1)(new StrMap({}))
) // StrMap { value: {} }
```

**Comment by leighman** [comment]
@gcanti any plan to add `At`/`Index` stuff? Wrote my own `Optional` for `Record<string, Blah>` but `Index` over `StrMap` would be much nicer.

**Comment by gcanti** [comment]
@leighman it's in my backlog, would you be happy to submit a PR?

**Comment by leighman** [comment]
I know nothing about lens laws or anything 😂 Will have a look at the Scala stuff this weekend and see what I can do.

**Comment by gcanti** [comment]
@leighman :) nevermind, I'll try to come up with something ASAP

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/monocle-ts/pull/48
