### ISSUE TITLE
Add alias `composeLens` for `compose` in `Lens` etc

### ISSUE THREAD

**Issue by leighman** [gcanti/monocle-ts#51]
If, for example, the object up my compose chain used to be a `Prism` I will later be calling it with `composeLens`. If I add something to provide a default value instead my object is now a `Lens` and `composeLens` fails (must be replaced with `compose`).

It would be nice if `composeLens` continued working.

Is this something that could be added? Would be happy to do it, if so.

**Comment by gcanti** [comment]
@leighman sorry for being so late (somehow I missed this issue), I've added some aliases here https://github.com/gcanti/monocle-ts/pull/72

**Comment by leighman** [comment]
Nice one. Thanks.
