### ISSUE TITLE
Updating fields of class instances drops their prototype, returning raw objects instead

### ISSUE THREAD

**Issue by treybrisbane** [gcanti/monocle-ts#52]
**monocle-ts version**: 1.2.0

**Reproduction**:
```es6
const { Lens } = require('monocle-ts');

class Foo {
    constructor(fooString) {
        this.fooString = fooString;
    }
}

class Bar {
    constructor(barString) {
        this.barString = barString;
    }
}

class FooBar {
    constructor(fooObject, barObject) {
        this.fooObject = fooObject;
        this.barObject = barObject;
    }
}

const fooBar = new FooBar(new Foo('foo string'), new Bar('bar string'));
const updatedFooBar = Lens.fromPath(['fooObject', 'fooString']).set('new foo string')(fooBar);

console.log(fooBar instanceof FooBar);
console.log(fooBar.fooObject instanceof Foo);
console.log(updatedFooBar instanceof FooBar);
console.log(updatedFooBar.fooObject instanceof Foo);
```

**Expected output**:
```
true
true
true
true
```

**Actual output**:
```
true
true
false
false
```

**Comment by gcanti** [comment]
@treybrisbane thanks for your PR but I'm not sure I want to support classes. 
Also looks like there's no prior art, the following libraries don't support classes as well

- ramda
- https://github.com/calmm-js/partial.lenses
- https://github.com/DrBoolean/lenses
- https://github.com/5outh/nanoscope

**Comment by treybrisbane** [comment]
@gcanti All the more reason to be the first! :P

But in all seriousness, the original Scala Monocle library supports classes (admittedly because Scala doesn't have native record types), so I feel like Monocle TS should also support them in some capacity...

Mind if I ask why you're hesitant? :)

**Comment by treybrisbane** [comment]
Something practical to also consider is that there is added incentive in both Flow and (to a lesser extent) TypeScript to use classes over objects. In Flow, classes are nominally typed (which I understand to be preferred for functional code), and in TypeScript you get some shorthand syntax when defining classes.

If you're _really_ against this, then I guess that's fair enough and we can close this, but I think we'd definitely add value by supporting classes by some means (even if that means a different approach to what I implemented in my PR). :)

**Comment by gcanti** [comment]
@treybrisbane I'm not against classes per se, it's just that

- there's no prior art (I wonder why) and I don't want to be the first (*)
- TypeScript's type system is structural, IME classes must be used carefully / sparingly
- technically it would be a breaking change unless we provide a polyfill for `Object.getOwnPropertyDescriptors`

(*) this is the main point

**Comment by treybrisbane** [comment]
@gcanti Reading into it a bit more, it looks like other libraries just leave class support up to the user via manual creation of lenses. It's not so much that they fundamentally don't support classes; just that their utility functions/methods don't.

After some thought, I agree with you that we shouldn't support classes in the way I suggested. :)

I'll use the library as-is for a bit, and see if a general pattern emerges for class support that I could more confidently propose for addition to the library, but until then we can probably close this.

**Comment by gcanti** [comment]
@treybrisbane ok, thanks again for opening this issue (and sending a related PR).
