### ISSUE TITLE
Bad Type Inference when using generics

### ISSUE THREAD

**Issue by benny-medflyt** [gcanti/monocle-ts#71]
Hi, I tried creating a lens for accessing elements of an array:

```ts
function arrayElem<T>(index: number): Lens<T[], T> {
    function get(s: T[]): T {
        return s[index];
    }

    function set(a: T): (s: T[]) => T[] {
        return (s: T[]): T[] => {
            const copy = [...s];
            copy[index] = a;
            return copy;
        };
    }

    return new Lens<T[], T>(get, set);
}
```

This works well:

```ts
const x = [[0, 1, 2], [3, 4, 5]];
const y = arrayElem(1).compose(arrayElem(2)).set(100)(x);
console.log(y); // [ [ 0, 1, 2 ], [ 3, 4, 100 ] ]
```

The only problem is that the type inference is messed up. TypeScript thinks that the type of `y` is `Array<{}>` (instead of `Array<Array<number>>`)

```ts
y[0][0] // Compile error!
```

Explicitly providing the type when calling arrayElem fixes things:

```ts
const y = arrayElem<Array<number>>(1).compose(arrayElem<number>(2)).set(100)(x);
```

But it is very annoying to have to explicitly gives types everywhere.

Is there a technique that can be used to create a Generic lens that works well with type inference? Thank you!

**Comment by gcanti** [comment]
> Is there a technique that can be used to create a Generic lens that works well with type inference? 

Not that I'm aware of, as soon as you call `arrayElem` without providing the type you are screwed

```ts
// const l: Lens<{}[], {}>
const l = arrayElem(1)
```

p.s.

Usually accessing elements of an array is not modeled by a `Lens` (it's an `Optional`), see https://github.com/gcanti/monocle-ts#indexarray

Example

```ts
import { indexArray } from 'monocle-ts/lib/Index/Array'

const x = [[0, 1, 2], [3, 4, 5]]

// const y: Optional<number[][], number>
const y = indexArray<Array<number>>()
  .index(1)
  .compose(indexArray<number>().index(2))
```

**Comment by benny-medflyt** [comment]
Thanks. `indexArray` suffers from the same type inference problem, correct?
