### ISSUE TITLE
Help targeting elements in array

### ISSUE THREAD

**Issue by alexandercrichton** [gcanti/monocle-ts#77]
Hi. I think this might've been addressed already (here: https://github.com/gcanti/monocle-ts/issues/73#issuecomment-450476198) but the usage is confusing me.

I just want to update a particular element in an array. For example:

```typescript
type Child = {
    readonly id: number;
    readonly value: string;
}

type Parent = {
    readonly children: ReadonlyArray<Child>;
}
```

What's the easiest/best way to just update (set) the value of the child with `id` of `1`? I'm just having trouble understanding all the options and which to use to achieve this. Do I use `Optional` if I only need to set (not get)?

Thanks!

**Comment by gcanti** [comment]
Here's my proposed solution

1) focus on the `children` field of `Parent` (Lens)

```ts
const children = Lens.fromProp<Parent>()('children') // Lens<Parent, Child[]>
```

2) focus on each `Child` in the array (Traversal)

```ts
const childTraversal = fromTraversable(array)<Child>() // Traversal<Child[], Child>
```

3) focus on a `Child` with some specific `id` (Prism)

```ts
const getChildPrism = (id: number): Prism<Child, Child> => Prism.fromPredicate(child => child.id === id)
```

4) focus on the `value` field of `Child` (Lens)

```ts
const value = Lens.fromProp<Child>()('value') // Lens<Child, string>
```

Now let's combine them together

```ts
const getChildTraversal = (id: number): Traversal<Parent, string> =>
  children
    .composeTraversal(childTraversal)
    .composePrism(getChildPrism(id))
    .composeLens(value)
```

Example

```ts
const parent: Parent = {
  children: [{ id: 1, value: 'child1' }, { id: 2, value: 'child2' }]
}

console.log(getChildTraversal(1).set('a')(parent))
// => { children: [ { id: 1, value: 'a' }, { id: 2, value: 'child2' } ] }

console.log(getChildTraversal(3).set('a')(parent))
// => { children: [ { id: 1, value: 'child1' }, { id: 2, value: 'child2' } ] }
```

**Comment by alexandercrichton** [comment]
Thanks @gcanti. Sorry I totally missed your response notification. 

I understand the example, thank you. 

When I try to use `import { array } from 'fp-ts/lib/Array'` it either breaks my TypeScript:
![image](https://user-images.githubusercontent.com/3139645/52825090-fff98300-3080-11e9-814b-32ab2cf14b72.png)
or TypeScript complains that it doesn't satisfy `Traversable<never>` or something (I haven't been able to capture that again).

Have you seen that before?

**Comment by gcanti** [comment]
> Have you seen that before?

@alexandercrichton yes, check for multiple versions of fp-ts, see the note here https://github.com/gcanti/fp-ts#typescript-compatibility

**Comment by alexandercrichton** [comment]
Thanks!

**Comment by iflp** [comment]
Hi @gcanti,

What if I wanted to focus on a Child at a specific array index, say the `head` or the 2nd element in the array, instead of a property `id`?

**Comment by gcanti** [comment]
@iflp see the `Index` abstraction, in particular the `'monocle-ts/lib/Index/Array'` module

```ts
import { indexArray } from 'monocle-ts/lib/Index/Array'

// fistChild: Optional<Child[], Child>
const fistChild = indexArray<Child>().index(0)
```

**Comment by iflp** [comment]
@gcanti That was exactly what I needed, thank you! As a beginner who is just diving into fp, I find myself struggling with what abstraction to use. I got confused trying to compose `At` and `Index`.

**Comment by iflp** [comment]
Hi @gcanti, 
```
      type Child = {
        readonly grandchildren: Grandchild[];
      };

      type Parent = {
        readonly children: Child[];
      };

      type Grandchild = {
        readonly value: string;
      };

      const firstChild = indexArray<Child>().index(0); //head
      const firstGrandchild = indexArray<Grandchild>().index(0); //head

      const children = Lens.fromProp<Parent>()('children'); // Lens<Parent, Child[]>
      const value = Lens.fromProp<Grandchild>()('value'); // Lens<Grandchild, string>
      
      const getFirstChildOfFirstChild= 
        children
        .composeOptional(firstChild)
        .composeOptional(firstGrandchild)
        .compose(value);
```

so I'm expecting this to work, but a type error was thrown. What would be the correct way to compose it?

**Comment by gcanti** [comment]
```ts
const grandchildren = Lens.fromProp<Child>()('grandchildren')

const getFirstChildOfFirstChild = children
  .composeOptional(firstChild)
  .composeLens(grandchildren)
  .composeOptional(firstGrandchild)
  .composeLens(value)
```
