### ISSUE TITLE
Monocle should not create new useless data structure

### ISSUE THREAD

**Issue by sledorze** [gcanti/monocle-ts#78]
For instance when a modify returns the element it was sent.
@gcanti I may provide a PR with those optimisation if accepted beforehand.

**Comment by gcanti** [comment]
> For instance when a modify returns the element it was sent

Some example?
Using `===` as equality?

**Comment by sledorze** [comment]
Some proposal are in the PR.

Note: I cannot run the test because of https://github.com/gcanti/monocle-ts/issues/80)

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/monocle-ts/pull/79

**Comment by gcanti** [comment]
@sledorze if you haven't anything to add I'll cut a new release

**Comment by gcanti** [comment]
@sledorze released, thanks a lot for your work!

**Comment by sledorze** [comment]
Seriously.. That s the other way around. Thanks a lot for constantly be so dedicated, logical and welcoming
