### ISSUE TITLE
Bug: modify alters functions (ie, `left` and `right` in data structure)

### ISSUE THREAD

**Issue by babakness** [gcanti/monocle-ts#92]
**Do you want to request a _feature_ or report a _bug_?**
BUG

**What is the current behavior?**

```ts
const data = {
  people: right( { images: ['foobar'] } ),
  animals: right(  { images: ['foobar'] } )
}
 
const newData = Lens.fromPath<typeof data>()(['people','value','images']).modify( _ => ['foobar'] )

newData.people.isRight === undefined
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

https://codesandbox.io/s/m9j0krw3j9

**What is the expected behavior?**

funcitons are preserved, data on branches not touched are not changed

**Which versions of monocle-ts, and which browser and OS are affected by this issue? Did this work in previous versions of monocle-ts?**

See codesandbox

**Comment by gcanti** [comment]
@babakness classes aren't supported.

Also, getting into a `Either` is modeled by a `Prism` rather than a `Lens`:

```ts
import { Either, right } from 'fp-ts/lib/Either'
import { Lens } from 'monocle-ts'
import { _right } from 'monocle-ts/lib/Either'

interface Images {
  images: Array<string>
}

interface Data {
  people: Either<string, Images>
  animals: Either<string, Images>
}

const data: Data = {
  people: right({ images: ['foobar'] }),
  animals: right({ images: ['foobar'] })
}

const people = Lens.fromProp<Data>()('people')
const value = _right<string, Images>() // <= a Prism
const images = Lens.fromProp<Images>()('images')
const peopleImages = people.composePrism(value).composeLens(images)

const x = peopleImages.modify(_ => ['foo'])(data)

console.log(x)
/*
{ people: right({
  "images": [
    "foo"
  ]
}),
  animals: right({
  "images": [
    "foobar"
  ]
}) }
*/
```
