### ISSUE TITLE
Tree map with identity should not return new object

### ISSUE THREAD

**Issue by steida** [gcanti/monocle-ts#99]
## 🐛 Bug report

Maybe I am overlooking something, but when there is no change, the tree should not be changed.
Now modify always changes everything. I suppose it should work like Lens.

```ts
interface User {
  name: string;
  age: number;
}

const tree1 = make({ name: 'Boss', age: 42 }, [
  make({ name: 'Manager1', age: 35 }, [
    make({ name: 'Emp1', age: 45 }),
    make({ name: 'Emp2', age: 64 }),
  ]),
]);

const hierarchyTraversal = fromTraversable(tree)<User>();
const tree2 = hierarchyTraversal.modify(identity)(tree1);
// Why it is false?
console.log(tree1 === tree2);
```

**Comment by DenisFrezzato** [comment]
The point of using lenses is to "modify" objects preserving immutability. `modify` applies a function to an object, returning a new object, no matter what the function does. There is no way to determine if a function is an `identity` function, so a new object is created anyway.

**Comment by steida** [comment]
But which immutability is preserved, when everything is changed no matter what function is used?

**Comment by steida** [comment]
But it should reuse structure as Lens with the PR https://github.com/gcanti/monocle-ts/pull/79 I suppose.
